### PR TITLE
Black as auto formatting tool

### PR DESCRIPTION
**Pull request by topless**
The only option used is --line-length 79 as defined in pep8.

### CODE REVIEW

**Comment by egabancho** [comment]
I remember talking with Lars some time ago about using Yapf from Google ... perhaps there is a good reason to use Black ☺️

**Comment by lnielsen** [comment]
Black looks great, but I'm a little concerned that the first version was released in March, and it's not stable yet (meaning). I'm fine with checking out the tool on Invenio-Circulation and later adopting it for all repositories (once stable), as long as PEP8 compliance is maintained.

**Comment by jma** [comment]
I think we need to also use `-S`  or `--skip-string-normalization` option as Invenio prefer single quote to double quote.
I installed the sublime version: https://github.com/jgirardet/sublack with this configuration:
```json
{
    "black_line_length": 79,
    "black_skip_string_normalization": true
}
```

**Comment by topless** [comment]
@lnielsen this PR was not intended to be merged but to demonstrate a small piece of code and its output in order to get a first idea if it fits with existing invenio conventions. As you stated the idea is to experiment with it on circulation and then we can evaluate its stability, or not. A super cool thing is that supports `isort` so with on step we can nail them both.
@jma single or double doesn't matter, as long as we all use the same.

**Comment by lnielsen** [comment]
> Invenio prefer single quote to double quote.

Since the tool is anyway going to touch many lines, and both are PEP8 compliant I'm fine with either as long as it is consistent and nothing is left to the developer. I prefer out-of-the-box defaults :-)

**Comment by topless** [comment]
There is a good [argument](https://github.com/ambv/black#line-length) for the default line length set to 88, but that would require to configure pep8 max-line-length (`E501`). Since its a radical change in the codebase maybe would be worth considering.

**Comment by lnielsen** [comment]
For the line length, I would stay with 79 as defined by PEP8.

**Comment by ntarocco** [comment]
To be adopted when code more "stable"

**Pull request closed without merging**
