### PR TITLE
transitions: remove reset of end_date when loan is returned

### PR DESCRIPTION
**Pull request by vgranata**
Remove the setting of end_date to transaction_date once the loan is returned.

Co-Authored-by: Valeria Granata <valeria@chaw.com>

### Description

To keep track of the end_date value once the loan is returned.

### Checklist

Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:

- [x] I'm aware of the [code of conduct](https://inveniordm.docs.cern.ch/contribute/code-of-conduct/).
- [x] I've created [logical separate commits](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commits) and followed the [commit message format](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commit-message).
- [x] I've added relevant test cases.
- [x] I've added relevant documentation.
- [x] I've marked [translation strings](https://inveniordm.docs.cern.ch/develop/best-practices/i18n/) (for relevant code).
- [x] I've followed the [CSS/JS](https://inveniordm.docs.cern.ch/develop/best-practices/css-js/) and [React](https://inveniordm.docs.cern.ch/develop/best-practices/react/) guidelines (for relevant code).
- [x] I've followed the [web accessibility](https://inveniordm.docs.cern.ch/develop/best-practices/accessibility/) guidelines (for relevant code).
- [x] I've followed the [user interface](https://inveniordm.docs.cern.ch/develop/best-practices/ui/) guidelines (for relevant code).
- [x] I've identified the [copyright holder(s)](https://inveniordm.docs.cern.ch/contribute/copyright-policy/) and updated copyright headers for touched files (>15 lines contributions).
- [x] I've NOT included third-party code (copy/pasted source code or new dependencies).

**Third-party code**

If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).

**Reminder**

By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:

1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license your contribution under the current repository’s license.

### CODE REVIEW

**Review by BadrAly — APPROVED** [review]
commit message: instead of loan is closed => loan is returned

**Comment by ntarocco** [comment]
@BadrAly thanks for the fix. Can you explain a little bit more why?
When a loan is completed, the `end_date` should be probably be set to the check-in moment. Is that not correct?
This might be a breaking change.

@ntarocco The use case, as presented by our PO,  requires to keep  records of the initial `end_date` of the checked-out loan. They want to be able to show both the `calculated_end_date` and the actual `check_in` date. If we apply the changes proposed by @vgranata, we can have access to both dates ( for loans with the state=`ITEM_RETURNED`):
1. `calculated_end_date` = loan.end_date
2. `checkin_date` = loan.transaction_date

**Comment by kpsherva** [comment]
if I understand correctly your use case, then isn't it enough to use `loan['end_date']` as the `checkin_date` and set the calculated_end_date initially, without changing it during the last transaction? Otherwise this is a breaking change for us.

**Comment by vgranata** [comment]
@kpsherva @ntarocco Thank you for your comments. We will find another solution.

**Pull request closed without merging**
