### PR TITLE
api: implement API GET request to fetch a loan

### PR DESCRIPTION
**Pull request by ntarocco**
* added extensions rest, records, records-rest, db, search, pidstore
* created basic configuration for REST calls
* created test to fetch a loan record
* fixed example app

Co-authored-by: Zacharias Zacharodimos <zacharias.zacharodimos@cern.ch>
Co-authored-by: Christos Topaloudis <topless@gmail.com>

### CODE REVIEW

**Comment by jma** [comment]
You have to sort correctly the import: try `isort -rc`.

**Comment by ntarocco** [comment]
@jma unfortunately on my Mac, I have `isort` not giving same results as Travis, so until I am able to fix it, I always need to wait Travis to see which ones are wrong.. thanks for commenting it but it will happen again :)

**Comment by jma** [comment]
@ntarocco ok no problem. But when I try to run `pytest` I got: 
```
Usage: flask fixtures [OPTIONS] COMMAND [ARGS]...

Error: No such command "loans".
```

**Comment by ntarocco** [comment]
@jma @Garfield-fr @BadrAly PR is ready!

**Comment by egabancho** [comment]
What do you think about using python 3.6 instead of 3.5 in Travis?

**Comment by ntarocco** [comment]
@egabancho yeah no problem! Do you see any particular reason? or it is just to be up-to-date?

**Comment by egabancho** [comment]
No, nothing special about it, just to stay updated. The last release for 3.5 is planed for August and it’s already in “security fixes” mode already (according to the docs), it seems natural to use 3.6 if possible.
Otherwise you can use 3.7, which was release a few days ago 😉

**Review by BadrAly — APPROVED** [review]

**Review by Garfield-fr — APPROVED** [review]

**Pull request merged**
